config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects
  resources :jobs

  namespace :admin do
    resource :users, controller: :users do
	    post :add_user_projects
      get :index
	  end
    root to: 'application#index'
  end
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
#
class Job < ApplicationRecord

  STATUSES = { 0 => 'unstarted', 1 => 'started', 2 => 'completed' }.freeze

  validates :title,       presence: true
  validates :description, presence: true
  validates :status,      presence: true

  belongs_to :project

  def humanize_status
    STATUSES[status]
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title,       presence: true
  validates :description, presence: true

  has_many  :user_projects
  has_many  :user, through: :user_projects

  has_many  :jobs

  def self.by_user_projects(user)
    user.projects
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_projects
  has_many :projects, through: :user_projects

  has_many :jobs
  
  validates_presence_of :first_name, :last_name
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/admin/admin_users_controller.rb
# module Admin
#   class AdminUsersController < Admin::ApplicationController
#     # To customize the behavior of this controller,
#     # simply overwrite any of the RESTful actions. For example:
#     #
#     # def index
#     #   super
#     #   @resources = AdminUser.all.paginate(10, params[:page])
#     # end
#
#     # Define a custom finder by overriding the `find_resource` method:
#     # def find_resource(param)
#     #   AdminUser.find_by!(slug: param)
#     # end
#     # See https://administrate-docs.herokuapp.com/customizing_controller_actions
#     # for more information
#
#     def index
#     end
#   end
# end

app/controllers/admin/application_controller.rb
# # All Administrate controllers inherit from this `Admin::ApplicationController`,
# # making it the ideal place to put authentication logic or other
# # before_filters.
# #
# # If you want to add pagination or other controller-level concerns,
# # you're free to overwrite the RESTful controller actions.
# module Admin
#   def self.admin_types
#     ['AdminUser']
#   end
#   class ApplicationController < ActionController::Base
#     before_action :authenticate_user!
#     before_action :authenticate_admin
#
#     def authenticate_admin
#       unless Admin.admin_types.include?(current_user.try(:type))
#         flash[:alert] = "Your are not authrize to acees the admin dashboard."
#         redirect_to(root_path)
#       end
#     end
#
#     def index
#       @projects = Project.all
#     end
#
#     # Override this value to specify the number of elements to display at a time
#     # on index pages. Defaults to 20.
#     # def records_per_page
#     #   params[:per_page] || 20
#     # end
#   end
# end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    def index
      @users = User.all
      @projects = Project.all
    end

    def new
      if current_user.type == 'AdminUser'
        @project = Project.new
        @projects = Project.by_user_projects(current_user)
      else
        render :index
      end
    end

    def create
      @project = Project.new(project_params)
      @project.save
      @user_projects = UserProject.create(user_project_params)
      if @project.save && @user_projects.save
        redirect_to @project, notice: 'Your Project was created successfully.'
      else
        redirect_to project_path
      end
    end

    def edit
      @project = Project.find(params[:id])
    end

    def update
      @project = Project.find(params[:id])
      if @project.update(project_params)
        redirect_to admin_users_path
      end
    end

    private


    def project_params
      params.require(:project).permit(:title, :description)
    end
  end
end

app/controllers/admin_users_controller.rb
  class AdminUserController < ActionController::Base



    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery with: :exception
    before_action :authenticate_user!

    def resource_params
      params.require(:user).permit(dashboard.permitted_attributes)
    end

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(root_path)
    end
end

app/controllers/jobs_controller.rb
# Job/Controoler
class JobsController < ApplicationController
  def create
    @job = Job.new(job_params)
    @job.save
    redirect_to project_path(@job.project)
  end

  def edit
    @projects = Project.by_user_projects(current_user)
    @jobs = Job.all
    @job = Job.find(params[:id])
    @statuses = Job::STATUSES
  end

  def update
    @job = Job.find(params[:id])
    @project = Project.by_user_projects(current_user)
    if @job.update(job_params)
      redirect_to project_path(@job.project)
    else
      render 'edit'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to project_path
  end

  private

  def job_params
    params.require(:job).permit(:project_id, :title, :description, :status)
  end
end

app/controllers/projects_controller.rb
# app/cojtrollers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.by_user_projects(current_user)
    @project = Project.new
  end

  def show
    @projects = Project.by_user_projects(current_user)
    @job = Job.new(status: 0)
    @statuses = Job::STATUSES
  end

  def new
    if current_user.type == 'AdminUser'
      @project = Project.new
      @projects = Project.by_user_projects(current_user)
    else
      render :index
    end
  end

  def create
    @project = Project.new(project_params)
    @project.save
    @user_projects = UserProject.create(project_id: @project.id, user_id: current_user.id)
    if @project.save && @user_projects.save
      redirect_to @project, notice: 'Your Project was created successfully.'
    else
      redirect_to project_path
    end
  end

  def edit
    authorize @project
    @projects = Project.by_user_projects(current_user)
  end

  def update
    authorize @project

    if @project.update(project_params)
      redirect_to @project
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

  def set_project

    @project = Project.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_projects, only: [:show,  :add_user_projects]
  def index
    @users = User.all
    @projects = Project.all
  end

  def new
    if current_user.type == 'AdminUser'
      @user = User.new
    else
      render :index
    end
  end

  def create
    @user = User.new(user_params)
    @user.id = User.last.id + 1
    @user.save
    if @user.save
      redirect_to admin_users_path, notice: 'Your Project was created successfully.'
    else
      redirect_to
    end
  end

  def add_user_projects
    @user_projects = UserProject.create!(user_id: params[:user][:user_id], project_id: params[:project][:project_id])
    @user_projects.save
    if @user_projects.save
      redirect_to admin_users_path, notice: 'Your Project was created successfully.'
    else
      redirect_to admin_users_path
    end
  end

  private

  def set_user_projects
    @user_projects = UserProject.all
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def admin?
    current_user.type == 'AdminUser'
  end

  def exist_project?
    current_user.projects.count > 0
  end
end

app/views/admin/application/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Infinity Admin" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div class="off-canvas-wrapper">
      <div class="off-canvas-wrapper-inner main-wrapper" data-off-canvas-wrapper>
        <div class="off-canvas position-left reveal-for-large left-navigation" id="my-info" data-off-canvas data-position="left">
          <div class="row column">
          <br>
          <%= link_to root_path, class: 'logo' do %>
            <%= image_tag 'logo' %>
            <% end %>
          <%#= render 'shared/menu' %>
          </div>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
          <div class="title-bar hide-for-large">
            <div class="title-bar-left">
              <button class="menu-icon" type="button" data-open="my-info"></button>
              <span class="title-bar-title">Infinity</span>
            </div>
          </div>

          <div class="callout">
            <div class="row expanded">
              <%#= render 'shared/menu-horizontal' %>
            </div>
          </div>
          <% end %>
          <div class="row main-render expanded">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/admin/projects/edit.html.erb
<%= form_for @project, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :description, size: "60x12" %>
  <%= f.submit "Update" %>
<% end %>

<%= link_to 'Back', projects_path %>

app/views/admin/projects/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Infinity Admin" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div class="off-canvas-wrapper">
      <div class="off-canvas-wrapper-inner main-wrapper" data-off-canvas-wrapper>
        <div class="off-canvas position-left reveal-for-large left-navigation" id="my-info" data-off-canvas data-position="left">
          <div class="row column">
          <br>
          <%= link_to root_path, class: 'logo' do %>
            <%= image_tag 'logo' %>
            <% end %>
          <%= render 'shared/menu' %>
          </div>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
          <div class="title-bar hide-for-large">
            <div class="title-bar-left">
              <button class="menu-icon" type="button" data-open="my-info"></button>
              <span class="title-bar-title">Infinity</span>
            </div>
          </div>

          <div class="callout">
            <div class="row expanded">
              <%= render 'shared/menu-horizontal' %>
            </div>
          </div>
          <% end %>
  
          <div class="row main-render expanded">
            <%= link_to 'Create user', new_admin_project_path %>
            <table>
              <thead>
                <tr>
                  <th width="150">First Name</th>
                  <th>Last name</th>
                  <th width="150">email</th>
                  <th width="150">Password</th>
                  <th width="150">Delete</th>

                </tr>
              </thead>
              <tbody>
                <% @projects.each do |project| %>
                  <tr>
                      <td><p><%= project.title %></p></td>
                      <td><p><%= project.description %></p></td>
                      <td><%= link_to 'Update', edit_admin_project_path(project)  %></td>
                      <td><%= link_to 'Show Details' %></td>
                      <td><%= button_to 'Delete Project', { action: 'destroy', id: project.id },
                                                     method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>


<html>

app/views/admin/projects/new.html.erb
<div class="reveal" id="newProject" data-reveal>
  <h1>New Project</h1>
  <hr />
  <%= form_for @project, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <div class="field columns">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field columns">
    <%= f.label :description %>
    <%= f.text_area :description, size: "15x12" %>
  </div>
    <%= f.submit "Create project" ,class: 'button pull-right'%>
  <% end %>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/admin/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Infinity Admin" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div class="off-canvas-wrapper">
      <div class="off-canvas-wrapper-inner main-wrapper" data-off-canvas-wrapper>
        <div class="off-canvas position-left reveal-for-large left-navigation" id="my-info" data-off-canvas data-position="left">
          <div class="row column">
          <br>
          <%= link_to root_path, class: 'logo' do %>
            <%= image_tag 'logo' %>
            <% end %>
          <%= render 'shared/menu' %>
          </div>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
          <div class="title-bar hide-for-large">
            <div class="title-bar-left">
              <button class="menu-icon" type="button" data-open="my-info"></button>
              <span class="title-bar-title">Infinity</span>
            </div>
          </div>

          <div class="callout">
            <div class="row expanded">
              <%= render 'shared/menu-horizontal' %>
            </div>
          </div>
          <% end %>
          <div class="callout">
            <div class="row expanded">
              <%= form_tag('/admin/users/add_user_projects', {:method => :post}) do %>

              <%= collection_select(:user, :user_id, User.all, :id, :email) %>

              <%= collection_select(:project, :project_id, Project.all, :id, :title) %>

            <%= submit_tag 'Asign user to project', class: 'button secondary' %>

              <% end %>
            </div>
          </div>
          <div class="row main-render expanded">
            <%= link_to 'Create user', new_admin_users_path %>
            <table>
              <thead>
                <tr>
                  <th width="150">First Name</th>
                  <th>Last name</th>
                  <th width="150">email</th>
                  <th width="150">Password</th>
                  <th width="150">Delete</th>
                  <th width="150">Delete</th>
                  <th width="150">Delete</th>
                </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                  <tr>
                      <td><p><%= user.first_name %></p></td>
                      <td><p><%= user.last_name %></p></td>
                      <td><p><%= user.email %></p></td>
                      <td><p><%= user.id %></p></td>
                      <td><%= link_to 'Update' %></td>
                      <td><%= link_to 'Show Details' %></td>
                      <td><%= button_to 'Delete Project', { action: 'destroy', id: user.id },
                                                     method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>


<html>

app/views/admin/users/new.html.erb
<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"}  do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>
   <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name, autofocus: true %>
    </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>


  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="project-section">
  <div class="medium-6 columns main-column-left">
    <div class="row">
      <div class="card columns main-column-row">
        <h5>SPRINT 1 STORIES</h5>
        <hr/>
        <ul class="menu expanded job-list">
          <li><%= @job.title %></li>
          <li><%= @job.description %></li>
          <li><%= @job.humanize_status %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="medium-6 columns main-column-right job-tasks">
    <div class="row">
      <div class="columns card">
      <%= form_for @job, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
        <%= f.text_field :title %>
        <%= f.text_area :description, size: "15x12" %>
        <%= f.select(:status, options_for_select(@statuses.invert)) %>
        <%= f.submit "Update", class: 'button secondary expanded' %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Infinity" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div class="off-canvas-wrapper">
      <div class="off-canvas-wrapper-inner main-wrapper" data-off-canvas-wrapper>
        <div class="off-canvas position-left reveal-for-large left-navigation" id="my-info" data-off-canvas data-position="left">
          <div class="row column">
          <br>
          <%= link_to root_path, class: 'logo' do %>
            <%= image_tag 'logo' %>
            <% end %>
          <%= render 'shared/menu' %>
          </div>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
          <div class="title-bar hide-for-large">
            <div class="title-bar-left">
              <button class="menu-icon" type="button" data-open="my-info"></button>
              <span class="title-bar-title">Infinity</span>
            </div>
          </div>

          <div class="callout">
            <div class="row expanded">
              <%= render 'shared/menu-horizontal' %>
            </div>
          </div>
          <% end %>
          <div class="row main-render expanded">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/projects/_create_job_form.html.erb
<div class="card columns">
  <h2>Create Job</h2>

  <%= form_for @job, url: jobs_path, html: {class: 'nifty_form'} do |f| %>
    <%= f.text_field :title, placeholder: 'Enter the project title..' %>
    <%= f.text_area :description, size: '8x8', placeholder: 'Enter the project description..' %>
    <%= f.select(:status, options_for_select(@statuses.invert), {include_blank: 'Select progress'} )  %>
    <%= f.hidden_field :project_id, type: 'hidden' , value: @project.id %>
    <%= f.submit 'Create', class: 'button expanded  secondary' %>
  <% end %>
</div>

app/views/projects/_display_jobs_table.html.erb
<h5>SPRINT 1</h5>
<hr/>

    <% jobs.each do |job| %>
      <%= link_to edit_job_path(job), class: '' do %>
      <ul class="menu expanded job-list">
          <li class="circle-icon"><p class=" fa fa-check-circle-o"></p></li>
          <li><p><%= job.title %></p></li>
          <li><p><%= job.description %></p></li>
          <li><p><%= job.humanize_status %></p></li>
          <li></li>
          <li><%= button_to 'Delete Job', { controller: :jobs , action: 'destroy', id: job.id },
                                         method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
      <% end %>
    <% end %>
</table>

app/views/projects/index.html.erb
<div class="clear fixed row">
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div class="row">
  <div class="medium-6 medium-offset-3 columns main-page">
    <h2 class="text-center">Welcome aboard!</h2>
    <h2 class="text-center">You have logged in Successfully</h2>
  </div>
</div>
<div class="row">
  <div class="medium-4 medium-offset-4 columns main-page">
    <% if admin? %>
      <%= link_to 'Get started, create new project', new_project_path , class: 'button expanded secondary hollow fa fa-plus-circle'%>
    <% end %>
  </div>
</div>
</div>
<% if exist_project? %>
<table>
  <thead>
    <tr>
      <th width="200">Project Title</th>
      <th>Project Description</th>
      <th width="150">Update</th>
      <th width="150">Show Details </th>
      <th width="150">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
          <td><p><%= project.title %></p></td>
          <td><p><%= project.description %></p></td>
          <td><%= link_to 'Update', edit_project_path(project) %></td>
          <td><%= link_to 'Show Details', project_path(project) %></td>
          <td><%= button_to 'Delete Project', { action: 'destroy', id: project.id },
                                         method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/projects/new.html.erb
<div class="reveal" id="newProject" data-reveal>
  <h1>New Project</h1>
  <hr />
  <%= form_for @project, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <div class="field columns">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field columns">
    <%= f.label :description %>
    <%= f.text_area :description, size: "15x12" %>
  </div>
    <%= f.submit "Create project" ,class: 'button pull-right'%>
  <% end %>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/projects/show.html.erb
<div class="project-section">
  <div class="medium-6 columns main-column-left">
    <div class="row">
      <div class="card columns main-column-row">
        <h2><%= @project.title %> stories</h2>
        <p><%= @project.description %></p>
        <%= link_to 'Add taks', '#' ,class: 'button hollow expanded  create-job text-left fa fa-plus-circle' %>
        <%= render partial: 'display_jobs_table' ,locals: {jobs: @project.jobs}%>
      </div>
    </div>
  </div>

  <div class="medium-6 columns main-column-right job-tasks">
    <div class="row">
      <%= render 'create_job_form' %>
    </div>
  </div>
</div>

app/views/shared/_dashboard.html.erb
<div class="off-canvas-wrapper">
  <div class="off-canvas-wrapper-inner main-wrapper" data-off-canvas-wrapper>
    <div class="off-canvas position-left reveal-for-large left-navigation" id="my-info" data-off-canvas data-position="left">
      <div class="row column">
      <br>
      <%= link_to root_path, class: 'logo' do %>
        <%= image_tag 'logo' %>
        <% end %>
      <%= render 'shared/menu' %>
      </div>
    </div>
    <div class="off-canvas-content" data-off-canvas-content>
      <div class="title-bar hide-for-large">
        <div class="title-bar-left">
          <button class="menu-icon" type="button" data-open="my-info"></button>
          <span class="title-bar-title">Infinity</span>
        </div>
      </div>

      <div class="callout">
        <div class="row column">
          <%= render 'shared/menu-horizontal' %>
        </div>
      </div>
      <div class="row">
        <h1>Hello! This is the project management app.</h1>
      </div>
    </div>
  </div>
</div>

app/views/shared/_menu-horizontal.html.erb
<ul class="menu align-right">
  <li><%= link_to 'Admin dashboard', admin_users_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'right'  %></li>
</ul>

app/views/shared/_menu.html.erb
<hr/>
<ul class="menu">
  <li><%= link_to 'Project', projects_path %></li>
  <li><i class="fa fa-plus-circle"></i></li>
</ul>
<ul class="menu vertical">

  <% if Project.by_user_projects(current_user) %>
    <%  @projects.each do |project| %>
      <li><%= link_to project.title, project_path(project), class: 'left-li-a fa fa-arrow-right'%><li>
    <% end %>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1> hey user</h1>